### ISSUE TITLE
Can't install at all

### ISSUE THREAD

**Issue by nam-drun** [tsinghua-ideal/Canvas#4]
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - cmake>=3.0
  - ninja
  - setuptools>=42
  - wheel
* Getting build dependencies for wheel...
running egg_info
writing Canvas.egg-info/PKG-INFO
writing dependency_links to Canvas.egg-info/dependency_links.txt
writing requirements to Canvas.egg-info/requires.txt
writing top-level names to Canvas.egg-info/top_level.txt
reading manifest file 'Canvas.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.h' under directory 'src'
warning: no files found matching 'LICENSE'
writing manifest file 'Canvas.egg-info/SOURCES.txt'
* Installing packages in isolated environment:
  - wheel
* Building wheel...
running bdist_wheel
running build
running build_py
copying canvas/kernel_pack.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/__init__.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/sample.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/runtime.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/placeholder.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/saver.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/utils.py -> build/lib.linux-x86_64-cpython-310/canvas
copying canvas/modules.py -> build/lib.linux-x86_64-cpython-310/canvas
running build_ext
compiling with RelBuildWithAsserts mode ...
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.10/dist-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 114, in <module>
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/tmp/build-env-q61gy80m/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "<string>", line 108, in build_extension
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/content/Canvas', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/content/Canvas/build/lib.linux-x86_64-cpython-310/', '-DPYTHON_EXECUTABLE=/tmp/build-env-q61gy80m/bin/python', '-DCMAKE_BUILD_TYPE=RelBuildWithAsserts', '-GNinja']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke build_wheel

**Comment by nam-drun** [comment]
I have managed to install it by making another .whl file my own
